=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class Barcode1DSymbology
    NONE = "None".freeze
    INDUSTRIAL2OF5 = "Industrial2of5".freeze
    INVERTED2OF5 = "Inverted2of5".freeze
    INTERLEAVED2OF5 = "Interleaved2of5".freeze
    IATA2OF5 = "Iata2of5".freeze
    MATRIX2OF5 = "Matrix2of5".freeze
    CODE39 = "Code39".freeze
    CODEABAR = "Codeabar".freeze
    BCD_MATRIX = "BcdMatrix".freeze
    DATA_LOGIC2OF5 = "DataLogic2of5".freeze
    CODE128 = "Code128".freeze
    CODE93 = "CODE93".freeze
    EAN13 = "EAN13".freeze
    UPCA = "UPCA".freeze
    EAN8 = "EAN8".freeze
    UPCE = "UPCE".freeze
    ADD5 = "ADD5".freeze
    ADD2 = "ADD2".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Barcode1DSymbology.constants.select { |c| Barcode1DSymbology::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Barcode1DSymbology" if constantValues.empty?
      value
    end
  end
end
