=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class ColorDepthConversionMethod
    DEPTH1_BPP = "Depth1Bpp".freeze
    DEPTH1_BPP_OTSU = "Depth1BppOtsu".freeze
    DEPTH1_BPP_BRADLEY = "Depth1BppBradley".freeze
    DEPTH1_BPP_SAUVOLA = "Depth1BppSauvola".freeze
    DEPTH1_BPP_FAST = "Depth1BppFast".freeze
    DEPTH4_BPP16 = "Depth4Bpp16".freeze
    DEPTH4_BPP_Q = "Depth4BppQ".freeze
    DEPTH8_BPP_GRAY_SCALE = "Depth8BppGrayScale".freeze
    DEPTH8_BPP_GRAY_SCALE_ADV = "Depth8BppGrayScaleAdv".freeze
    DEPTH8_BPP216 = "Depth8Bpp216".freeze
    DEPTH8_BPP_Q = "Depth8BppQ".freeze
    DEPTH16_BPP_RGB555 = "Depth16BppRGB555".freeze
    DEPTH16_BPP_RGB565 = "Depth16BppRGB565".freeze
    DEPTH24_BPP_RGB = "Depth24BppRGB".freeze
    DEPTH32_BPP_ARGB = "Depth32BppARGB".freeze
    DEPTH32_BPP_RGB = "Depth32BppRGB".freeze
    DEPTH32_BPP_PARGB = "Depth32BppPARGB".freeze
    DEPTH48_BPP_RGB = "Depth48BppRGB".freeze
    DEPTH64_BPP_ARGB = "Depth64BppARGB".freeze
    DEPTH64_BPP_PARGB = "Depth64BppPARGB".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ColorDepthConversionMethod.constants.select { |c| ColorDepthConversionMethod::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ColorDepthConversionMethod" if constantValues.empty?
      value
    end
  end
end
