=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class DocumentFormat
    UNKNOWN = "UNKNOWN".freeze
    ICO = "ICO".freeze
    BMP = "BMP".freeze
    WBMP = "WBMP".freeze
    JPEG = "JPEG".freeze
    GIF = "GIF".freeze
    PNG = "PNG".freeze
    TIFF = "TIFF".freeze
    FAXG3 = "FAXG3".freeze
    EXIF = "EXIF".freeze
    EMF = "EMF".freeze
    WMF = "WMF".freeze
    JNG = "JNG".freeze
    KOALA = "KOALA".freeze
    IFF = "IFF".freeze
    MNG = "MNG".freeze
    PCD = "PCD".freeze
    PCX = "PCX".freeze
    PBM = "PBM".freeze
    PBMRAW = "PBMRAW".freeze
    PFM = "PFM".freeze
    PGM = "PGM".freeze
    PGMRAW = "PGMRAW".freeze
    PPM = "PPM".freeze
    PPMRAW = "PPMRAW".freeze
    RAS = "RAS".freeze
    TARGA = "TARGA".freeze
    PSD = "PSD".freeze
    CUT = "CUT".freeze
    XBM = "XBM".freeze
    XPM = "XPM".freeze
    DDS = "DDS".freeze
    HDR = "HDR".freeze
    SGI = "SGI".freeze
    EXR = "EXR".freeze
    J2_K = "J2K".freeze
    JP2 = "JP2".freeze
    PICT = "PICT".freeze
    RAW = "RAW".freeze
    WEBP = "WEBP".freeze
    DICOM = "DICOM".freeze
    JBIG = "JBIG".freeze
    JBIG2 = "JBIG2".freeze
    WSQ = "WSQ".freeze
    PDF = "PDF".freeze
    SVG = "SVG".freeze
    TXT = "TXT".freeze
    DOCX = "DOCX".freeze
    RTF = "RTF".freeze
    DXF = "DXF".freeze
    ODT = "ODT".freeze
    XLSX = "XLSX".freeze
    PPTX = "PPTX".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DocumentFormat.constants.select { |c| DocumentFormat::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DocumentFormat" if constantValues.empty?
      value
    end
  end
end
