=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  # Represents information about the layout of a content, on the page it is drawn onto.
  class DrawableContentLayoutParameters
    attr_accessor :horizontal_position

    attr_accessor :vertical_position

    attr_accessor :size

    # Specifies whether the content shall be slightly indented from the nearest page edges.
    attr_accessor :indent_from_edges

    # Specifies the absolute horizontal position of the top-left edge of the content, in points.
    attr_accessor :absolute_position_left

    # Specifies the absolute vertical position of the top-left edge of the content, in points.
    attr_accessor :absolute_position_top

    # Specifies the absolute width of the content, in points.
    attr_accessor :absolute_width

    # Specifies the absolute height of the content, in points.
    attr_accessor :absolute_height

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'horizontal_position' => :'HorizontalPosition',
        :'vertical_position' => :'VerticalPosition',
        :'size' => :'Size',
        :'indent_from_edges' => :'IndentFromEdges',
        :'absolute_position_left' => :'AbsolutePositionLeft',
        :'absolute_position_top' => :'AbsolutePositionTop',
        :'absolute_width' => :'AbsoluteWidth',
        :'absolute_height' => :'AbsoluteHeight'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'horizontal_position' => :'ContentHorizontalPosition',
        :'vertical_position' => :'ContentVerticalPosition',
        :'size' => :'ContentSize',
        :'indent_from_edges' => :'Boolean',
        :'absolute_position_left' => :'Float',
        :'absolute_position_top' => :'Float',
        :'absolute_width' => :'Float',
        :'absolute_height' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::DrawableContentLayoutParameters` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::DrawableContentLayoutParameters`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'horizontal_position')
        self.horizontal_position = attributes[:'horizontal_position']
      end

      if attributes.key?(:'vertical_position')
        self.vertical_position = attributes[:'vertical_position']
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'indent_from_edges')
        self.indent_from_edges = attributes[:'indent_from_edges']
      else
        self.indent_from_edges = true
      end

      if attributes.key?(:'absolute_position_left')
        self.absolute_position_left = attributes[:'absolute_position_left']
      end

      if attributes.key?(:'absolute_position_top')
        self.absolute_position_top = attributes[:'absolute_position_top']
      end

      if attributes.key?(:'absolute_width')
        self.absolute_width = attributes[:'absolute_width']
      end

      if attributes.key?(:'absolute_height')
        self.absolute_height = attributes[:'absolute_height']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          horizontal_position == o.horizontal_position &&
          vertical_position == o.vertical_position &&
          size == o.size &&
          indent_from_edges == o.indent_from_edges &&
          absolute_position_left == o.absolute_position_left &&
          absolute_position_top == o.absolute_position_top &&
          absolute_width == o.absolute_width &&
          absolute_height == o.absolute_height
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [horizontal_position, vertical_position, size, indent_from_edges, absolute_position_left, absolute_position_top, absolute_width, absolute_height].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        OpenapiClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
