=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class PdfAConformance
    PDFA1A = "PDFA1a".freeze
    PDFA1B = "PDFA1b".freeze
    PDFA2A = "PDFA2a".freeze
    PDFA2B = "PDFA2b".freeze
    PDFA2U = "PDFA2u".freeze
    PDFA3A = "PDFA3a".freeze
    PDFA3B = "PDFA3b".freeze
    PDFA3U = "PDFA3u".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PdfAConformance.constants.select { |c| PdfAConformance::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PdfAConformance" if constantValues.empty?
      value
    end
  end
end
