=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class PdfInitViewLayoutMode
    SINGLE_PAGE = "SinglePage".freeze
    ONE_COLUMN = "OneColumn".freeze
    TWO_COLUMN_LEFT = "TwoColumnLeft".freeze
    TWO_COLUMN_RIGHT = "TwoColumnRight".freeze
    TWO_PAGE_LEFT = "TwoPageLeft".freeze
    TWO_PAGE_RIGHT = "TwoPageRight".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PdfInitViewLayoutMode.constants.select { |c| PdfInitViewLayoutMode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PdfInitViewLayoutMode" if constantValues.empty?
      value
    end
  end
end
