=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class ResizeMode
    AUTO = "Auto".freeze
    NEAREST_NEIGHBOR = "NearestNeighbor".freeze
    BOX = "Box".freeze
    LANCZOS3 = "Lanczos3".freeze
    BILINEAR = "Bilinear".freeze
    BICUBIC = "Bicubic".freeze
    BSPLINE = "Bspline".freeze
    CATMULL_ROM_SPLINE = "CatmullRomSpline".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ResizeMode.constants.select { |c| ResizeMode::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ResizeMode" if constantValues.empty?
      value
    end
  end
end
