=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module OpenapiClient
  class StickyNoteAnnotationIcon
    COMMENT = "Comment".freeze
    KEY = "Key".freeze
    NOTE = "Note".freeze
    HELP = "Help".freeze
    NEW_PARAGRAPH = "NewParagraph".freeze
    PARAGRAPH = "Paragraph".freeze
    INSERT = "Insert".freeze
    CHECK = "Check".freeze
    CIRCLE = "Circle".freeze
    CROSS = "Cross".freeze
    CROSS_HAIRS = "CrossHairs".freeze
    RIGHT_ARROW = "RightArrow".freeze
    RIGHT_POINTER = "RightPointer".freeze
    STAR = "Star".freeze
    UP_ARROW = "UpArrow".freeze
    UP_LEFT_ARROW = "UpLeftArrow".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = StickyNoteAnnotationIcon.constants.select { |c| StickyNoteAnnotationIcon::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #StickyNoteAnnotationIcon" if constantValues.empty?
      value
    end
  end
end
