=begin
#PassportPDF API

#Another brick in the cloud

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PassportManagerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PassportManagerApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PassportManagerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PassportManagerApi' do
    it 'should create an instance of PassportManagerApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PassportManagerApi)
    end
  end

  # unit tests for passport_manager_get_passport_info
  # @param passport_id 
  # @param [Hash] opts the optional parameters
  # @return [PassportPDFPassport]
  describe 'passport_manager_get_passport_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
